env: "prod"
storage_path: "postgres://murad:123@db:5432/postgres?sslmode=disable"
http_server:
    host: "0.0.0.0:8080"
    timeout: 4s
    idle_timeout: 60s
    user: "myuser"
    password: "mypass"
    cors_allowed_origins:
      - "https://hyorward.tech"
      - "https://www.hyorward.tech"
      - "http://hyorward.tech"
      - "http://www.hyorward.tech"
    ws_allowed_origins:
      - "https://hyorward.tech"
      - "https://www.hyorward.tech"
      - "http://hyorward.tech"
      - "http://www.hyorward.tech"
jwt_secret: "change-me-to-a-real-secret"
jwt_access_expiration_in_minutes: 10080
jwt_refresh_expiration_in_minutes: 43200